# .github/workflows/codeQuality.yml

name: Project Quality Check

on: 
  push:
    branches: ["Dev"]
  pull_request:
    branches: ["Dev"]

jobs:
  run-shared-quality-check:
    uses: SurajPrajapati79/Code-Quality-Check/.github/workflows/main.yml@main
    with:
      backend_dir: "backend"
      frontend_dir: "frontend"
      python_version: "3.11"
      node_version: "20"
      backend_requirements: "backend/requirements.txt"
      run_pytest: true
