name: Code Quality Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black mypy ruff

      # Show Black formatting diffs in logs
      - name: Run Black (show required changes)
        run: black --check --diff .

      # Ruff replaces Flake8 and adds inline GitHub annotations
      - name: Run Ruff (linting with inline annotations)
        run: |
          ruff check . --output-format=github

      # Type checking with Mypy
      - name: Run Mypy (type checking)
        run: mypy .
